<script setup lang="ts">
import { computed } from 'vue'; import { RouterLink, useRoute } from 'vue-router'; import { Home, ListTodo, CalendarDays, Bot, MessageSquare, Cable, Cpu, Settings, Wifi, WifiOff, Bell } from 'lucide-vue-next'; import { useAppStore } from '../stores/app'
const app = useAppStore(); const route = useRoute(); const items = [{ to:'/', label:'总览', icon:Home }, { to:'/tasks', label:'任务', icon:ListTodo }, { to:'/calendar', label:'日历', icon:CalendarDays }, { to:'/messages', label:'消息', icon:MessageSquare }, { to:'/agent', label:'AI 助手', icon:Bot }, { to:'/connections', label:'连接', icon:Cable }, { to:'/providers', label:'模型提供商', icon:Cpu }, { to:'/settings', label:'设置', icon:Settings }]; const title = computed(() => items.find(i => i.to === route.path)?.label || '总览')
</script>
<template>
  <a class="skip-link" href="#main-content">跳到主要内容</a><div class="app-shell">
    <aside class="sidebar" aria-label="主导航"><div class="brand"><span class="brand-mark">C</span><span>CampusCue</span></div><div class="workspace-label">我的校园工作台</div><nav><RouterLink v-for="item in items" :key="item.to" :to="item.to" :aria-current="route.path === item.to ? 'page' : undefined"><component :is="item.icon" :size="18" stroke-width="1.8" /><span>{{ item.label }}</span></RouterLink></nav><div class="sidebar-foot"><div class="system-pill"><span class="status-dot" :class="{ offline: !app.online }"></span><span>{{ app.online ? '本地服务正常' : '正在重连服务' }}</span></div><button class="nav-link theme-toggle" @click="app.setTheme(app.theme === 'light' ? 'dark' : 'light')"><Bell :size="17" /><span>{{ app.theme === 'light' ? '切换深色模式' : '切换浅色模式' }}</span></button></div></aside>
    <main id="main-content" class="main-column"><header class="topbar"><div><p class="eyebrow">{{ title }}</p><h1>{{ title }}</h1></div><div class="topbar-actions"><div class="connection-indicator" :class="{ offline: !app.online }"><component :is="app.online ? Wifi : WifiOff" :size="15" />{{ app.online ? '已连接' : '离线' }}</div><button class="avatar" aria-label="用户菜单">P</button></div></header><slot /></main>
    <nav class="mobile-nav" aria-label="移动端主导航"><RouterLink v-for="item in items.slice(0, 5)" :key="item.to" :to="item.to" :aria-label="item.label"><component :is="item.icon" :size="20" /><span>{{ item.label }}</span></RouterLink></nav><div v-if="app.notice" class="toast" role="status">{{ app.notice }}</div>
  </div>
</template>
