<script setup lang="ts">
import { ref } from 'vue'
import { api } from '../api/client'
import type { Source, Task, TaskCategory, TaskPriority, TaskStatus } from '../types/api'
const props = defineProps<{ task?: Task | null; sources: Source[] }>(); const emit = defineEmits<{ saved: [task: Task]; close: [] }>()
const saving = ref(false); const error = ref(''); const title = ref(props.task?.title || ''); const description = ref(props.task?.description || ''); const category = ref<TaskCategory>(props.task?.category || 'other'); const course = ref(props.task?.course || ''); const deadline = ref(props.task?.deadline ? props.task.deadline.slice(0, 16) : ''); const priority = ref<TaskPriority>(props.task?.priority || 'normal'); const status = ref<TaskStatus>(props.task?.status || 'pending');
async function save() { if (!title.value.trim() || saving.value) return; saving.value = true; error.value = ''; try { const body = { title: title.value.trim(), description: description.value.trim() || null, category: category.value, course: course.value.trim() || null, deadline: deadline.value ? new Date(deadline.value).toISOString() : null, priority: priority.value, source_id: props.task?.source_id || null, status: props.task ? status.value : undefined }; const task = props.task ? await api.updateTask(props.task.id, body) : await api.createTask(body); emit('saved', task) } catch (e) { error.value = e instanceof Error ? e.message : '保存失败' } finally { saving.value = false } }
</script>
<template><form class="task-editor" @submit.prevent="save"><div v-if="error" class="form-error" role="alert">{{ error }}</div><label>标题<input v-model="title" required maxlength="256" autofocus /></label><label>描述<textarea v-model="description" rows="3" placeholder="可选" /></label><div class="form-grid"><label>类型<select v-model="category"><option value="homework">作业</option><option value="exam">考试</option><option value="competition">比赛</option><option value="activity">活动</option><option value="notice">通知</option><option value="other">其他</option></select></label><label>优先级<select v-model="priority"><option value="low">低</option><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option></select></label><label>课程<input v-model="course" placeholder="可选" /></label><label>截止时间<input v-model="deadline" type="datetime-local" /></label><label v-if="task">状态<select v-model="status"><option value="pending_confirm">待确认</option><option value="pending">进行中</option><option value="done">已完成</option><option value="dismissed">已忽略</option></select></label></div><p class="form-help">清空截止时间会向 M5 发送明确的 null，表示清除；未编辑字段不会被误改。</p><div class="form-actions"><button type="button" class="button button-secondary" @click="emit('close')">取消</button><button class="button button-primary" :disabled="saving">{{ saving ? '保存中…' : '保存任务' }}</button></div></form></template>
