<script setup lang="ts">
import { Check, Circle, Clock3, MoreHorizontal } from 'lucide-vue-next'
import type { Task } from '../types/api'
import { formatDate, formatTime } from '../composables/useFormat'
import { taskCategoryLabel, taskStatusLabel } from '../utils/taskLabels'
const props = withDefaults(defineProps<{ task: Task; showDismiss?: boolean }>(), { showDismiss: true })
const emit = defineEmits(['complete', 'dismiss'])
function deadlineTone(deadline?: string | null) { if (!deadline) return ''; const delta = new Date(deadline).getTime() - Date.now(); if (delta < 0) return 'deadline-overdue'; if (delta <= 86_400_000) return 'deadline-critical'; if (delta <= 604_800_000) return 'deadline-soon'; return '' }
</script>
<template><article class="task-row" :class="[`task-${props.task.status}`, { overdue: props.task.deadline && new Date(props.task.deadline) < new Date() && (props.task.status === 'pending' || props.task.status === 'pending_confirm') } ]" :data-testid="`task-${props.task.id}`"><button class="task-check" :aria-label="props.task.status === 'done' ? '已完成' : `完成任务：${props.task.title}`" @click="emit('complete')"><Check v-if="props.task.status === 'done'" :size="15" /><Circle v-else :size="17" /></button><div class="task-main"><h3>{{ props.task.title }}</h3><p><span v-if="props.task.course" class="task-course">{{ props.task.course }}</span><span v-if="props.task.course && props.task.deadline"> · </span><span class="task-category" :class="props.task.category">{{ taskCategoryLabel(props.task.category) }}</span><span v-if="taskStatusLabel(props.task.status)" class="task-status-badge">{{ taskStatusLabel(props.task.status) }}</span></p></div><div v-if="props.task.deadline" class="task-deadline" :class="deadlineTone(props.task.deadline)"><Clock3 :size="14" /><span>{{ formatDate(props.task.deadline) }}</span><small>{{ formatTime(props.task.deadline) }}</small></div><button v-if="props.showDismiss && props.task.status !== 'done' && props.task.status !== 'dismissed'" class="icon-button" :aria-label="`忽略任务：${props.task.title}`" @click="emit('dismiss')"><MoreHorizontal :size="18" /></button></article></template>
