export type Page<T> = { items: T[]; total: number; limit: number; offset: number }
export type TaskStatus = 'pending_confirm' | 'pending' | 'done' | 'dismissed'
export type TaskCategory = 'homework' | 'exam' | 'competition' | 'activity' | 'notice' | 'other'
export type TaskPriority = 'low' | 'normal' | 'high'
export type Task = { id: number; title: string; description: string | null; category: TaskCategory; course: string | null; deadline: string | null; status: TaskStatus; priority: TaskPriority; confidence: number | null; source_id: number | null; source_message_id: string | null; source_text_reference: string | null; created_at: string; updated_at: string }
export type TaskWrite = { title: string; description?: string | null; category: TaskCategory; course?: string | null; deadline?: string | null; priority: TaskPriority; source_id?: number | null; status?: TaskStatus }
export type Source = { id: number; platform: string; conversation_id: string; name: string; enabled: boolean; auto_extract: boolean; context_window: number; privacy_policy: string; created_at: string; updated_at: string; deleted_at: string | null }
export type SourceWrite = { platform?: string; conversation_id?: string; name?: string; enabled?: boolean; auto_extract?: boolean; context_window?: number; privacy_policy?: string }
export type SourceTest = { ok: boolean; reachable: boolean; latency_ms: number | null; error_category: string | null; message: string }
export type Message = { id: number; source_id: number | null; source_message_id: string; created_at: string; status: string; confidence: number | null; had_task: boolean; task_id: number | null; reason: string | null; text_retained: boolean; retained_text: string | null }
export type MessageDetail = Message & { normalized_result: Record<string, unknown> | null; audit: Record<string, unknown> | null; error: string | null }
export type Provider = { id: number; name: string; provider_type: string; base_url: string; model: string; temperature: number | null; max_tokens: number | null; max_context_tokens: number | null; timeout_s: number; secret_reference: string | null; enabled: boolean; created_at: string; updated_at: string }
export type ProviderWrite = { name: string; provider_type?: string; base_url: string; model: string; temperature?: number | null; max_tokens?: number | null; max_context_tokens?: number | null; timeout_s?: number; secret_reference?: string | null; enabled?: boolean }
export type ProviderTest = { ok: boolean; latency_ms: number | null; error_category: string | null; message: string }
export type Reminder = { id: number; task_id: number; trigger_at: string; type: string; status: string; last_run: string | null; error: string | null; created_at: string; updated_at: string }
export type SettingsValue = { timezone: string; theme: 'system' | 'light' | 'dark'; message_retention_days: number; reminder_default_enabled: boolean; reminder_min_lead_seconds: number; reminder_quiet_start_hour: number; reminder_quiet_end_hour: number }
export type Settings = { settings: SettingsValue; restart_required: string[] }
export type Health = { status: string; runtime: string; database: string; adapter: string; reminders: string; agent: string; api: string }
export type SystemStatus = { runtime: string; uptime_seconds: number; components: Record<string, unknown>; feature_flags: Record<string, boolean>; provider_configured: boolean; adapter_connected: boolean }
export type LogItem = { level?: string; component?: string; message?: string; timestamp?: string; [key: string]: unknown }
export type Logs = Page<LogItem>
export type Backup = { format_version: number; schema_version: number; created_at: string; version: string; data: Record<string, unknown> }
export type ImportResult = { created: number; skipped: number; duplicates: number; errors: Array<{ title?: string; error?: string; [key: string]: string | undefined }> }
