<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'
import { Sparkles, Send, RotateCcw } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'; import { useResourcesStore } from '../stores/resources'; import { api } from '../api/client'; import { useAppStore } from '../stores/app'
const resources = useResourcesStore(); const app = useAppStore(); const text = ref(''); const sending = ref(false); const conversation = ref(''); const sourceId = ref<number | null>(null); const messages = ref<Array<{ role:'user'|'assistant'; text:string; tools?:string[]}>>([]); const scroller = ref<HTMLElement>()
onMounted(async () => { await resources.loadSources(); sourceId.value = resources.sources.find(s => s.enabled)?.id || null })
async function send() { const source = resources.sources.find(s => s.id === sourceId.value && s.enabled); if (!source || !text.value.trim() || sending.value) return; const prompt = text.value.trim(); text.value = ''; messages.value.push({ role:'user', text:prompt }); sending.value = true; try { const result = await api.agentChat({ source_id: source.id, conversation_id: conversation.value || undefined, message: prompt }); conversation.value = result.conversation_id; messages.value.push({ role:'assistant', text: result.message, tools: result.tool_activity }) } catch (e) { messages.value.push({ role:'assistant', text:e instanceof Error ? e.message : '助手暂时不可用' }) } finally { sending.value = false; await nextTick(); scroller.value?.scrollTo({ top:scroller.value.scrollHeight, behavior:'smooth' }) } }
</script>
<template><section class="page-content agent-page"><PageHeader eyebrow="CampusCue AI" title="AI 助手" description="用自然语言整理校园事务，助手只会基于当前选中的消息源工作。"><div class="agent-head-actions"><label v-if="resources.sources.filter(s => s.enabled).length > 1" class="source-selector"><span>当前来源</span><select v-model="sourceId"><option v-for="source in resources.sources.filter(s => s.enabled)" :key="source.id" :value="source.id">{{ source.name || source.conversation_id }}</option></select></label><button class="button button-secondary" @click="messages = []; conversation = ''"><RotateCcw :size="16" />新对话</button></div></PageHeader><section class="agent-shell panel"><div ref="scroller" class="chat-scroll"><div v-if="!messages.length" class="agent-welcome"><div class="agent-mark"><Sparkles :size="25" /></div><h2>今天想先理清什么？</h2><p>{{ sourceId ? '当前来源已选定。可以问我这周的截止时间，或描述一条校园事务。' : '请先在连接页启用一个消息源。' }}</p><div class="prompt-chips"><button :disabled="!sourceId" @click="text = '帮我梳理这周的截止时间'">梳理这周截止时间</button><button :disabled="!sourceId" @click="text = '我应该先做什么？'">我应该先做什么？</button></div></div><article v-for="(message,index) in messages" :key="index" class="chat-message" :class="message.role"><div class="chat-avatar"><Sparkles v-if="message.role === 'assistant'" :size="15" /><span v-else>P</span></div><div class="chat-bubble"><p>{{ message.text }}</p><div v-if="message.tools?.length" class="tool-activity"><span>执行记录</span><small v-for="tool in message.tools" :key="tool">{{ tool }}</small></div></div></article><div v-if="sending" class="chat-message assistant"><div class="chat-avatar"><Sparkles :size="15" /></div><div class="chat-bubble pending-dots"><i></i><i></i><i></i></div></div></div><form class="chat-composer" @submit.prevent="send"><label class="sr-only" for="agent-input">对 AI 助手说</label><textarea id="agent-input" v-model="text" :disabled="sending || !sourceId" rows="1" placeholder="描述一件校园事务…" @keydown.enter.exact.prevent="send"></textarea><button class="send-button" :disabled="!text.trim() || sending || !sourceId" aria-label="发送" type="submit"><Send :size="17" /></button></form></section></section></template>
