<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { CalendarDays, ChevronLeft, ChevronRight, Clock3 } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import EmptyState from '../components/EmptyState.vue'
import { useTasksStore } from '../stores/tasks'
import { formatDate, formatTime } from '../composables/useFormat'
import { taskCategoryLabel } from '../utils/taskLabels'
const store = useTasksStore(); const todayKey = key(new Date()); const selectedDay = ref(todayKey); const cursor = ref(new Date(new Date().getFullYear(), new Date().getMonth(), 1))
const monthLabel = computed(() => new Intl.DateTimeFormat('zh-CN', { year:'numeric', month:'long' }).format(cursor.value))
const monthStart = computed(() => new Date(cursor.value.getFullYear(), cursor.value.getMonth(), 1)); const monthEnd = computed(() => new Date(cursor.value.getFullYear(), cursor.value.getMonth() + 1, 0, 23, 59, 59))
const cells = computed(() => { const first = monthStart.value.getDay() || 7; const days = monthEnd.value.getDate(); const result: Array<{ date: Date; current: boolean }> = []; for (let i = 1; i < first; i++) result.push({ date: new Date(cursor.value.getFullYear(), cursor.value.getMonth(), i - first + 1), current:false }); for (let day = 1; day <= days; day++) result.push({ date: new Date(cursor.value.getFullYear(), cursor.value.getMonth(), day), current:true }); while (result.length % 7) { const next = result.length - (first - 1) - days + 1; result.push({ date: new Date(cursor.value.getFullYear(), cursor.value.getMonth() + 1, next), current:false }) } return result })
function key(date: Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}` }
const tasksByDay = computed(() => { const map = new Map<string, typeof store.items>(); for (const task of store.items) if (task.deadline) { const k = key(new Date(task.deadline)); map.set(k, [...(map.get(k) || []), task].sort((a,b) => (a.deadline || '').localeCompare(b.deadline || ''))) } return map })
const selectedTasks = computed(() => tasksByDay.value.get(selectedDay.value) || [])
const monthTasks = computed(() => [...tasksByDay.value.entries()].filter(([k]) => k.startsWith(`${cursor.value.getFullYear()}-${String(cursor.value.getMonth()+1).padStart(2,'0')}`)).flatMap(([, items]) => items).sort((a,b) => (a.deadline || '').localeCompare(b.deadline || '')))
const selectedLabel = computed(() => new Intl.DateTimeFormat('zh-CN', { month:'long', day:'numeric', weekday:'long' }).format(new Date(`${selectedDay.value}T12:00:00`)))
async function load() { await store.load(`deadline_from=${encodeURIComponent(monthStart.value.toISOString())}&deadline_to=${encodeURIComponent(monthEnd.value.toISOString())}&limit=200`) }
onMounted(load); watch(cursor, load); function move(delta:number) { cursor.value = new Date(cursor.value.getFullYear(), cursor.value.getMonth() + delta, 1); selectedDay.value = key(cursor.value) }; function today() { cursor.value = new Date(new Date().getFullYear(), new Date().getMonth(), 1); selectedDay.value = key(new Date()) }
</script>
<template><section class="page-content calendar-page"><PageHeader eyebrow="时间线" title="日历" description="把带截止时间的事项放在一张可浏览的月历里。"><div class="calendar-controls"><button class="icon-button" aria-label="上个月" @click="move(-1)"><ChevronLeft :size="18" /></button><button class="button button-secondary" @click="today">今天</button><button class="icon-button" aria-label="下个月" @click="move(1)"><ChevronRight :size="18" /></button></div></PageHeader><section class="calendar-hero panel"><div class="calendar-heading"><CalendarDays :size="21" /><div><strong>{{ monthLabel }}</strong><span>{{ store.loading ? '正在读取截止时间…' : '点击日期查看当天安排' }}</span></div><span class="cue-mark" aria-hidden="true"><i></i><b></b></span></div><div class="month-grid"><div v-for="day in ['一','二','三','四','五','六','日']" :key="day" class="month-weekday">{{ day }}</div><div v-for="cell in cells" :key="cell.date.toISOString()" class="month-cell" :class="{ muted: !cell.current, today: key(cell.date) === todayKey, selected: key(cell.date) === selectedDay }" role="button" tabindex="0" @click="selectedDay = key(cell.date)" @keydown.enter="selectedDay = key(cell.date)"><span>{{ cell.date.getDate() }}</span><div v-if="tasksByDay.get(key(cell.date))" class="day-tasks"><i v-for="task in tasksByDay.get(key(cell.date))?.slice(0,3)" :key="task.id" :class="`priority-${task.priority}`" :title="task.title"></i><b v-if="(tasksByDay.get(key(cell.date))?.length || 0) > 3">+{{ (tasksByDay.get(key(cell.date))?.length || 0) - 3 }}</b></div></div></div></section><section class="calendar-agenda panel"><div class="agenda-heading"><div><p class="section-kicker">选中日期</p><h3>{{ selectedLabel }}</h3></div><span>{{ selectedTasks.length }} 项</span></div><div v-if="selectedTasks.length" class="agenda-list"><article v-for="task in selectedTasks" :key="task.id" class="agenda-item"><span class="calendar-rule"></span><div><strong>{{ task.title }}</strong><p>{{ task.course || taskCategoryLabel(task.category) }}</p></div><time><Clock3 :size="14" />{{ formatTime(task.deadline) }}</time></article></div><EmptyState v-else variant="calendar" title="这一天没有排期" description="选择其他日期，或给任务加上截止时间。" /></section><section class="calendar-list" v-if="monthTasks.length"><h3>本月截止事项</h3><article v-for="task in monthTasks" :key="task.id" class="calendar-task"><span class="calendar-rule"></span><time class="calendar-date">{{ formatDate(task.deadline) }}</time><div><strong>{{ task.title }}</strong><p>{{ task.course || taskCategoryLabel(task.category) }}</p></div><span class="calendar-time"><Clock3 :size="14" />{{ formatTime(task.deadline) }}</span></article></section></section></template>
