<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { MessageSquareText, ArrowUpRight, X } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import EmptyState from '../components/EmptyState.vue'
import AppDialog from '../components/AppDialog.vue'
import { useResourcesStore } from '../stores/resources'
import { api } from '../api/client'
import type { Message, MessageDetail } from '../types/api'
import { formatDate, formatTime } from '../composables/useFormat'
const store = useResourcesStore(); const status = ref(''); const hadTask = ref(''); const confidence = ref(''); const selected = ref<MessageDetail | null>(null); const loadingDetail = ref(false)
async function load() { const q = new URLSearchParams(); if (status.value) q.set('had_task', status.value === 'task' ? 'true' : 'false'); if (confidence.value) q.set('confidence_min', confidence.value); q.set('limit','100'); await store.loadMessages(q.toString()) }
onMounted(load); watch([status, confidence], load)
async function open(message: Message) { loadingDetail.value = true; try { selected.value = await api.message(message.id) } finally { loadingDetail.value = false } }
</script>
<template><section class="page-content"><PageHeader eyebrow="消息处理" title="消息" description="查看哪些消息被识别、哪些消息生成了任务。"><button class="button button-secondary" @click="load"><MessageSquareText :size="16" />刷新</button></PageHeader><div class="message-filters panel"><label>状态<select v-model="status"><option value="">全部</option><option value="task">已生成任务</option><option value="none">未生成任务</option></select></label><label>最低置信度<select v-model="confidence"><option value="">不限</option><option value="0.5">50%</option><option value="0.8">80%</option><option value="0.9">90%</option></select></label><span class="muted-copy">只显示应用保留的结构化结果</span></div><section class="panel"><div class="list-heading"><strong>{{ store.messages.length }} 条处理记录</strong><span v-if="loadingDetail" class="loading-label">正在打开详情…</span></div><div v-if="store.messages.length" class="message-table"><article v-for="message in store.messages" :key="message.id" :class="['message-card', 'clickable', message.status]" tabindex="0" @click="open(message)" @keydown.enter="open(message)"><div class="message-icon"><MessageSquareText :size="17" /></div><div class="message-card-main"><div class="message-card-title"><strong>{{ message.had_task ? '已提取任务' : '已处理消息' }}</strong><span class="status-badge" :class="message.status">{{ message.status }}</span></div><p>{{ message.retained_text || '原文未保留，仅保存结构化处理结果。' }}</p><small>{{ formatDate(message.created_at) }} {{ formatTime(message.created_at) }} · 来源 #{{ message.source_id ?? '未知' }} · {{ message.confidence == null ? '无置信度' : `置信度 ${(message.confidence * 100).toFixed(0)}%` }}</small><span v-if="message.confidence != null" class="confidence-meter" :aria-label="`置信度 ${(message.confidence * 100).toFixed(0)}%`"><i :style="{ width: `${Math.round(message.confidence * 100)}%` }"></i></span></div><ArrowUpRight :size="16" class="quiet-icon" /></article></div><EmptyState v-else title="还没有消息记录" description="连接消息源并启用自动提取后，这里会出现处理结果。" /></section><AppDialog :open="Boolean(selected)" title="消息处理详情" description="结构化结果与隐私保留状态" @close="selected = null"><div v-if="selected" class="detail-list"><div><span>状态</span><strong>{{ selected.status }}</strong></div><div><span>识别置信度</span><strong>{{ selected.confidence == null ? '未提供' : `${(selected.confidence * 100).toFixed(0)}%` }}</strong></div><div><span>任务关系</span><strong>{{ selected.task_id ? `任务 #${selected.task_id}` : '未创建任务' }}</strong></div><div><span>处理原因</span><strong>{{ selected.reason || selected.error || '无额外说明' }}</strong></div><div class="retention-note"><span><X v-if="!selected.text_retained" :size="15" /><MessageSquareText v-else :size="15" />{{ selected.text_retained ? '原文按保留策略保存' : '原文未保留，符合隐私设置' }}</span></div></div></AppDialog></section></template>
