<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { MessageSquareText, ArrowUpRight } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import EmptyState from '../components/EmptyState.vue'
import AppDialog from '../components/AppDialog.vue'
import MessageInspector from '../components/MessageInspector.vue'
import { useResourcesStore } from '../stores/resources'
import { api } from '../api/client'
import type { Message, MessageDetail } from '../types/api'
import { formatDate, formatTime } from '../composables/useFormat'
const store = useResourcesStore(); const status = ref(''); const confidence = ref(''); const selected = ref<MessageDetail | null>(null); const loadingDetail = ref(false); const isMobile = ref(false)
function updateViewport() { isMobile.value = window.innerWidth < 900 }
async function load() { const q = new URLSearchParams(); if (status.value) q.set('had_task', status.value === 'task' ? 'true' : 'false'); if (confidence.value) q.set('confidence_min', confidence.value); q.set('limit','100'); await store.loadMessages(q.toString()); if (!selected.value && store.messages[0]) void open(store.messages[0]) }
onMounted(() => { updateViewport(); window.addEventListener('resize', updateViewport); void load() }); onUnmounted(() => window.removeEventListener('resize', updateViewport)); watch([status, confidence], load)
async function open(message: Message) { loadingDetail.value = true; try { selected.value = await api.message(message.id) } finally { loadingDetail.value = false } }
</script>
<template><section class="page-content messages-page"><PageHeader eyebrow="消息处理" title="消息" description="先看处理结果，需要时再打开单条消息的上下文。"><button class="button button-secondary" @click="load"><MessageSquareText :size="16" />刷新</button></PageHeader><div class="message-filters panel"><label>状态<select v-model="status"><option value="">全部</option><option value="task">已生成任务</option><option value="none">未生成任务</option></select></label><label>最低置信度<select v-model="confidence"><option value="">不限</option><option value="0.5">50%</option><option value="0.8">80%</option><option value="0.9">90%</option></select></label><span class="muted-copy">只显示应用保留的结构化结果</span></div><div class="message-workspace"><section class="panel signal-workspace"><div class="list-heading"><strong>{{ store.messages.length }} 条处理记录</strong><span v-if="loadingDetail" class="loading-label">正在打开详情…</span></div><div v-if="store.messages.length" class="message-table"><article v-for="message in store.messages" :key="message.id" :class="['message-card', 'clickable', message.status, { selected: selected?.id === message.id }]" tabindex="0" @click="open(message)" @keydown.enter="open(message)"><div class="message-icon"><MessageSquareText :size="17" /></div><div class="message-card-main"><div class="message-card-title"><strong>{{ message.had_task ? '已提取任务' : '已处理消息' }}</strong><span class="status-badge" :class="message.status">{{ message.status }}</span></div><p>{{ message.retained_text || '原文未保留，仅保存结构化处理结果。' }}</p><small>{{ formatDate(message.created_at) }} {{ formatTime(message.created_at) }} · {{ message.confidence == null ? '无置信度' : `置信度 ${(message.confidence * 100).toFixed(0)}%` }}</small><span v-if="message.confidence != null" class="confidence-meter" :aria-label="`置信度 ${(message.confidence * 100).toFixed(0)}%`"><i :style="{ width: `${Math.round(message.confidence * 100)}%` }"></i></span></div><ArrowUpRight :size="16" class="quiet-icon" /></article></div><EmptyState v-else variant="message" title="暂无处理记录" description="连接消息源并启用自动提取后，这里会出现结构化结果。"><RouterLink class="text-link" to="/connections">连接消息源 <ArrowUpRight :size="14" /></RouterLink></EmptyState><p class="privacy-hint">CampusCue 只展示结构化识别结果，原文是否保留由隐私策略决定。</p></section><aside v-if="selected && !isMobile" class="panel message-inspector"><div class="inspector-heading"><div><p class="section-kicker">处理详情</p><h3>这条消息做了什么</h3></div><MessageSquareText :size="19" /></div><MessageInspector :message="selected" /></aside></div><AppDialog :open="Boolean(selected) && isMobile" title="消息处理详情" description="结构化结果与隐私保留状态" @close="selected = null"><MessageInspector v-if="selected" :message="selected" /></AppDialog></section></template>
